### ISSUE TITLE
Support Forestry.io

### ISSUE THREAD

**Issue by DirtyF** [MadeByMike/supermaya#15]
👋 Hi, 

I've setup[ Forestry.io](https://forestry.io) with your starter, it offers a nice UI to edit content and preview before publishing.

![supermaya-forestry](https://user-images.githubusercontent.com/103008/68954150-b1217b00-07c3-11ea-9a2e-895a0dc30941.png)

I could open a PR with Forestry config and **Import to Forestry** button to the README to ease the process.

**Comment by MadeByMike** [comment]
Hey, I'm glad this was simple and I want to make it easy to use tools like Forestry.io and Netlify CMS, Contentful (or others) but I don't want to lock people into a platform. Especially where the data is stored on a third-party server as is the case with Forestry.io and Contentful. 

I want people to own their own data and services, that's why I made the Keystone backend. You could turn this into a CMS that powers 11ty. Or use mark-down, or NetlifyCMS where the data is still stored in markdown on your GitHub. If none of that works, that's ok but I want people to make the choice to use a third-party service on their own.

**Comment by DirtyF** [comment]
> the data is stored on a third-party server as is the case with Forestry.io 

For the record, Forestry is a Git-based CMS, and does not store any data, all content lies in your git repository.

**Comment by MadeByMike** [comment]
@DirtyF, Ahhh thanks for the clarification, it's been a while since I used Forestry.
